# Generated by Django 4.2.6 on 2023-11-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customer_created_customer_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='login',
        ),
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(max_length=50, verbose_name='Your login'),
        ),
    ]
