# Generated by Django 4.2.6 on 2023-11-27 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customer_login_alter_customer_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
