# Generated by Django 4.2.6 on 2023-11-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbshop', '0002_alter_goods_options_rename_name_goods_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.FloatField(verbose_name='Price in cents'),
        ),
    ]
