# Generated by Django 4.2.6 on 2023-11-06 18:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dbshop', '0003_alter_goods_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
