# Generated by Django 4.2.6 on 2023-11-06 19:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dbshop', '0004_goods_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='date',
        ),
        migrations.AddField(
            model_name='goods',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.FloatField(verbose_name='Price in USD'),
        ),
    ]
