# Generated by Django 4.2.6 on 2023-11-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbshop', '0006_goods_pic_alter_goods_created_alter_goods_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='pic',
            field=models.ImageField(default='404.webp', upload_to='uploads', verbose_name='Picture of a good'),
        ),
    ]
