# Generated by Django 4.2.6 on 2023-11-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbshop', '0007_alter_goods_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last updated'),
        ),
    ]
