# Generated by Django 4.2.6 on 2023-11-11 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbshop', '0008_alter_goods_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='updated',
            field=models.DateTimeField(verbose_name='Last updated'),
        ),
    ]
