# Generated by Django 4.2.6 on 2023-11-11 19:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dbshop', '0010_alter_goods_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last updated'),
            preserve_default=False,
        ),
    ]
