# Generated by Django 4.2.6 on 2023-11-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbshop', '0011_alter_goods_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='author',
            field=models.CharField(default='admin', max_length=50, verbose_name='Created by'),
        ),
    ]
