# Generated by Django 4.2.6 on 2023-11-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbshop', '0012_goods_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='author',
            field=models.CharField(max_length=50, verbose_name='Created by'),
        ),
    ]
